name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./RepertoriumAPI/RepertoriumAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: api-artifact
          path: ${{ env.DOTNET_ROOT }}/api
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: api-artifact
    - name: Azure WebApp deploy
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2.2.6
      with:
        app-name: 'repertorium-api-dev'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Prod'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: api-artifact
    - name: Azure WebApp deploy
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2.2.6
      with:
        app-name: 'repertorium-api-prod'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}

